### ISSUE TITLE
Configuração do Environment para Deploy

### ISSUE THREAD

**Issue by thiagoloureiro** [ThiagoBarradas/DotNet.WebApi.AppVeyor.Demo#1]
Olá Thiago, cheguei aqui no seu repo pesquisando exatamente como fazer deploy de uma WebAPI para um servidor.

Eu faço o build, no meu caso é apenas via FTP,, ele chega a enviar um ZIP lá pro meu FTP e só.

Como você faz para publicar sem ser o zip?
Abs!

**Comment by ThiagoBarradas** [comment]
Olá, tudo bem Xará? 😎

Primeiramente desculpe pela demora, por algum motivo a notificação da Issue passou batida.

Se ainda precisar da solução para fazer deploy via FTP, segue um exemplo bem fácil de entender, que você deverá por na etapa de deploy.

```yml
deploy:
  provider: FTP
  protocol: ftp
  host: ftp.seusite.com
  username: meuusuario
  password:
    secure: AABBBCCCC123==
  folder: wwwroot
  artifact: DotNet.WebApi.AppVeyor.Demo.zip
  application: DotNet.WebApi.AppVeyor.Demo.zip
```

Além das configurações da conexão, você irá informar `artifact` que deve ser o nome do artefato que será feito o upload (pode ser mais de um) e o `application` é o nome do artefato que, após o upload, será descompactado dentro do local setado em `folder`.

Acredito que a sua dúvida, "publicar sem ser o zip" se resolva com o parâmetro `application`.

Para gerar o `secure` da sua senha, acesse https://ci.appveyor.com/tools/encrypt após estar logado e gere o valor pelo AppVeyor.

Também tem na documentação oficial do AppVeyor.

https://www.appveyor.com/docs/deployment/ftp/

Espero que seja útil, abraços!
